### ISSUE TITLE
关于 book 中使用的数据

### ISSUE THREAD

**Issue by Tendo33** [djhcod/r-notes#1]
可不可以发一个Windows 版本的，或者放到github里面，Applecloud是真的难顶

**Comment by djhcod** [comment]
由于是GitHub免费账户😅，对文件大小有限制，所以现已将原始数据文件上传到[阿里云盘](https://www.alipan.com/s/2pqtEP8bxQM)，以供Windows用户下载。相关链接已在README文件和[前言](https://djhcod.github.io/r-notes/intro.html)中更新。

**Comment by Tendo33** [comment]
OK感谢！看来我来早了，那我再等等🤣
